---

  - name: >-
      prepare writing to hashivault secret store
    set_fact:
      smabot_hashivault_readwrite_secrets_args: >-
        {{ _iter_secret_stores | smabot.git.to_hashivault_cfg(write=True) }}
     no_log: true


  - ansible.builtin.include_role:
      name: smabot.hashivault.readwrite_secrets

