---

##gitlab_cfg:
##
##  servers:
##
##    instances:
##
##      <id/name>:
##
##        users:
##
##          bots:
##
##          humans:


  - smabot.gitlab.normalize_gitlab_cfg:
    register: _tmp_normres

  - set_fact:
      gitlab_cfg_normed: "{{ _tmp_normres.normalized }}"


  - include_task: handle_server_instance.yml
    loop: "{{ gitlab_cfg_normed.servers.instances | dict2items() }}"
    loop_control:
      loop_var: _server_iter

