---

  - set_fact:
      _tmp_secret_type: token
      _tmp_new_user_token: >-
        {{ _tmp_token_credmap[_item_pa_token.value.name].token }}
    no_log: true


  - include_tasks: ../../secret_stores/collect_secrets/main.yml
    loop: >-
      {{ _item_pa_token.value.stores
       | dict2items() | map(attribute='value') }}
    loop_control:
      loop_var: _iter_secret_stores


  - set_fact:
      _tmp_new_user_token:

