---

  - set_fact:
      _tmp_cur_cred: >-
         {{ _iter_gitsrv_users.value.credentials.password }}
      _tmp_secret_type: password


  - name: use preset password verbatim
    set_fact:
      _tmp_new_user_pw: >-
         {{ _tmp_cur_cred.value }}
    no_log: true
    when: not _tmp_cur_cred.auto_create.enabled


  - block:

       ## credentials prepare section: for auto cycling case try to read current secret from default store
       - block:

           - set_fact:
               _tmp_secret_setvar: _tmp_new_user_pw

           - include_tasks: ../secret_stores/read_secrets/main.yml
             loop: >-
               {{ [_tmp_cur_cred._default_store] }}
             loop_control:
               loop_var: _iter_secret_stores

         when: not _tmp_cur_cred.auto_create.cycle


       - name: auto generate new password for user
         set_fact:
           _tmp_new_user_pw: >-
             {{ lookup('ansible.builtin.password', '/dev/null',
                  **_tmp_cur_cred.auto_create.config) }}
         no_log: true
         when: not _tmp_new_user_pw


       ## collect new user secret so we can later push it to defined secret stores
       - include_tasks: ../secret_stores/collect_secrets/main.yml
         loop: >-
           {{ _tmp_cur_cred.stores | dict2items() | map(attribute='value') }}
         loop_control:
           loop_var: _iter_secret_stores

    when: _tmp_cur_cred.auto_create.enabled

